function(load_env_file filename)
  file(STRINGS ${filename} env_vars)
  foreach(line ${env_vars})
    string(REGEX MATCH "^([^=]+)=(.*)$" matched ${line})
    if(matched)
      set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()